version: "3"

services:

  show:
    image: aegeanstudio/solr-ik:8.3.0.0
    user: "8983:8983"
    restart: always
    volumes:
      - $PWD/show/var/solr:/var/solr:Z
      - $PWD/show/external:/external:Z
    ports:
      - 8984:8984
    container_name: show 
    networks:
      - show
    environment:
      - ZK_HOST=zoo:2181/solr/show
      - SOLR_HEAP=4g
      - SOLR_PORT=8984
    depends_on:
      - zoo1

  zoo1:
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    container_name: zoo
    hostname: zoo
    networks:
      - solr_haozan_show
    volumes:
      - $PWD/zk1/data:/data:Z
      - $PWD/zk1/datalog:/datalog:Z
      - $PWD/zk1/logs/:/logs:Z
      - $PWD/conf:/conf:Z

networks:
  solr_haozan_show:
    driver: bridge
