version: '3.8'

services:
  mysql:
    image: mysql:8.0.20
    container_name: mysql
    volumes:
      - $PWD/data:/var/lib/mysql:Z
    ports:
      - 3306:3306
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
