version: "3.7"

services:

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

networks:
  default:
    external:
      name: bridge_default
